build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371